Name : Sparsh Kumar


Roll : 1024170310


Batch : 3Q31

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like: 

a) Addition of 2 in all the element  

b) Multiply 3 with all the elements 

c) Divide every element by 2 

In [1]:
import numpy as np

In [2]:
a= np.array(np.arange(0,5))
a

array([0, 1, 2, 3, 4])

In [3]:
a+2

array([2, 3, 4, 5, 6])

In [4]:
a*3

array([ 0,  3,  6,  9, 12])

In [5]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [6]:
arr = np.array([1,2,3,6,4,5])
rev  = np.flip(arr)
rev

array([5, 4, 6, 3, 2, 1])

Q.2 Questions on Basic NumPy Array: 

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 

b) Find the most frequent value and their indice(s) in the following arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1]) ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 

In [7]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows: 

a) Access 1st row, 2nd column  

b) Access 3rd row, 1st column 

In [39]:
uniq,idx,counts = np.unique(x,return_counts=True,return_index=True)
most_freq = [uniq[i] for i in range(len(uniq)) if counts[i] == np.max(counts)]
print(f'Most freq element : {[i.item() for i in most_freq]}')
print([i for i in range(len(x)) if x[i] in  most_freq])

Most freq element : [1]
[0, 5, 7, 8, 9]


In [38]:
uniq,idx,counts = np.unique(y,return_counts=True,return_index=True)
most_freq = [uniq[i] for i in range(len(uniq)) if counts[i] == np.max(counts)]
print(f'Most freq element : {[i.item() for i in most_freq]}')
print([i for i in range(len(y)) if y[i] in  most_freq])

Most freq element : [1, 3]
[0, 1, 2, 4, 8, 9]


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute? 

In [14]:
sparsh = np.linspace(10,100,25)
print(f'Dims : {sparsh.shape}')
print(f'Size : {sparsh.size}')
print(f'Dtype : {sparsh.dtype}')
print(f'Bytes : {sparsh.nbytes}')


Dims : (25,)
Size : 25
Dtype : float64
Bytes : 200


In [20]:
sparsh.reshape(-1,1)

array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

In [31]:
print('To use new .T')
sparsh_1= sparsh[np.newaxis,:]
sparsh_1.T

To use new .T


array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>. 

In [64]:
ucs420_sparsh=np.array([10,20,30,40,50,60,70,80,90,15,20,35]).reshape(3,4).copy()
print(f'Mean : {np.mean(ucs420_sparsh)}')
print(f'Median : {np.max(ucs420_sparsh)}')
print(f'Min : {np.min(ucs420_sparsh)}')
print(f'Unique elemnts : {np.unique(ucs420_sparsh)}')
reshaped_ucs420_sparsh=ucs420_sparsh.reshape(4,3)
print(f'New Array : \n{reshaped_ucs420_sparsh}')
resized_ucs420_sparsh=ucs420_sparsh.copy()
resized_ucs420_sparsh.resize(2,3)
print(f'New Array : \n{resized_ucs420_sparsh}')




Mean : 43.333333333333336
Median : 90
Min : 10
Unique elemnts : [10 15 20 30 35 40 50 60 70 80 90]
New Array : 
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
New Array : 
[[10 20 30]
 [40 50 60]]
